//-----------------------------------------------------------------------------
// Copyright 2022 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//-----------------------------------------------------------------------------

#include "src/analysis/souffle/fact_test_helper.dl"

/*
  This macro makes it easy to ensure that:
  1. the `relation` exists exactly `n` times for the given `operation`,
  2. and that all of those `n` match the `expected` pattern.

  This checks that there are no unexpected solutions, for the `relation` for the
  given operation.
*/ 
#define TEST_N_RESULT_FOR_OPERATION(n, test_name, operation, relation, expected) \
  TEST_CASE(cat(test_name, cat("_", #relation))) :- \
    count : { relation(operation, expected) } = n, \
    count : { relation(operation, _) } = n

#define TEST_N_PREDICATE_FOR_OPERATION(n, test_name, operation, relation) \
  TEST_CASE(cat(test_name, cat("_", #relation))) :- \
    operationHasResult(operation, result), \
    count : { relation(result) } = n