#ifndef SENSITIVITY_ANALYSIS_UNIT_TEST_INTERFACE_DL_
#define SENSITIVITY_ANALYSIS_UNIT_TEST_INTERFACE_DL_

#include "src/analysis/souffle/sensitivity_analysis.dl"

//An interface used for unit testing of the sensitivity analysis. 
//Only outputs value sensitivities

.input isOperation(delimiter=";")
.input isInitialInput(delimiter=";")
.output sqlValueSensitivity(delimiter=";")

#endif SENSITIVITY_ANALYSIS_UNIT_TEST_INTERFACE_DL_