//-----------------------------------------------------------------------------
// Copyright 2022 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//-----------------------------------------------------------------------------

#ifndef SRC_ANALYSIS_SOUFFLE_SQL_VERIFIER_UNIT_TEST_INTERFACE
#define SRC_ANALYSIS_SOUFFLE_SQL_VERIFIER_UNIT_TEST_INTERFACE

#include "src/analysis/souffle/sql_output.dl"
#include "src/analysis/souffle/taint.dl"
#include "src/analysis/souffle/tag_transforms.dl"

// An interface used for running and getting results from the SQL verifier. Does
// not concern itself with authorization logic facts, considers only
// `Operation`s and `SqlPolicyRule`s. Returns as output the sqlOutputResult
// relation, which indicates which sql outputs were tainted and which ones were
// not tainted
.input isOperation(delimiter=";")
.input isSqlPolicyRule(delimiter=";")
.output sqlOutputResult(delimiter=";")

#endif
