# A Raksha parser for SQL using ZetaSQL

cc_test(
    name = "sql_parser_test",
    srcs = ["sql_parser_test.cc"],
    deps = [
        "//src/common/testing:gtest",
        "@com_google_absl//absl/strings",
        "@com_google_zetasql//zetasql/public:parse_helpers",
    ],
)
