steps:
# Pull most recent Docker image.
- id: 'pull-image'
  name: 'gcr.io/cloud-builders/docker'
  args: ['pull', '${_DOCKER_IMAGE}']
  waitFor: ['-']

# Build the new Docker image (caching from the pre-built one)
- id: 'build-image'
  waitFor: ['pull-image']
  name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '--network=cloudbuild',
    '--cache-from=${_DOCKER_IMAGE}',
    '--tag=${_DOCKER_IMAGE}',
    '.',
  ]

# Run presubmit tests.
- id: 'presubmit'
  waitFor: ['build-image']
  name: '${_DOCKER_IMAGE}'
  entrypoint: 'bash'
  args: ['./gcb/presubmit.sh']

# Push updated Docker image to Container Registry.
- id: 'push-image'
  waitFor: ['presubmit']
  name: 'gcr.io/cloud-builders/docker'
  args: [
    'push',
    '${_DOCKER_IMAGE}',
  ]

timeout: 3600s # 60 mins, just in case.

substitutions:
  _DOCKER_IMAGE: us-central1-docker.pkg.dev/google.com/raksha-ci/gcb-docker-images/gcb:latest
