//-----------------------------------------------------------------------------
// Copyright 2021 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//-----------------------------------------------------------------------------

#include "../taint.dl"
#include "../flat_graph_ir.dl"
#include "../edges_from_graph.dl"

// This is a datalog file that is meant to test taint_with_auth_logic.dl. It 
// should eventually be replaced by or otherwise used as a part of an
// automated test.

//-----------------------------------------------------------------------------
// Program Manifests
//-----------------------------------------------------------------------------

// Module 1
//      reads: 
//          some_struct{ a, b }
//          other_input
//      writes:
//          mod1out
bindFlatParticle("module1", $FlatParticle(
    /* reads */
    $Cons("some_struct.a", $Cons("some_struct.b",
        $Cons("other_input", $Nil()))),
    /* writes */
    $Cons("mod1out", $Nil())
)).

// the label of "other_input" is the empty set (which makes it public).
// so it has no label elements

// Module 2
//     reads:
//         mod1out
//         input4
//     writes:
//         mod2out 
bindFlatParticle("module2", $FlatParticle(
    /* reads */
    $Cons("mod1out", $Cons("input4", $Nil())),
    /* writes */
    $Cons("mod2out", $Nil())
)).

//-----------------------------------------------------------------------------
// Policy
//-----------------------------------------------------------------------------

// Assign owners to tags
ownsTag("Alice", "raw_video").
ownsTag("Alice", "image_selection").
ownsTag("Alice", "product_id").
ownsTag("ServiceProvider", "model_weights").

// Assign tags to initial inputs
claimHasTag("some_struct.a", "raw_video").
claimHasTag("some_struct.b", "image_selection").
claimHasTag("input4", "model_weights").

// The label of mod1out is downgraded to public (= empty set) 
// because both the raw_video and image_selection tags are removed, and then
// upgraded to {"product_id"} with this line:
claimHasTag("mod1out", "product_id").

// Set the downgrades permitted by both parties
saysDowngrades("Alice", "mod1out", "raw_video").
saysDowngrades("Alice", "mod1out", "image_selection").
saysDowngrades("ServiceProvider", "mod2out", "model_weights").

//----------------------------------------------------------------------------- 
// Policy Check
//-----------------------------------------------------------------------------

.decl test_label_check(x: number)

// Define a label for doing the check of the final output
isIFCLabel("mod2out_expected_label").
isMember("product_id", "mod2out_expected_label").

// The check passes if this is true (i.e., the CSV for test_label_check 
// includes '1').
// It is supposed to pass. If you comment out any of the "saysDowngrades" lines 
// above, it should fail.
test_label_check(1) :- accessPathLabelFlowsTo("mod2out", 
                            "mod2out_expected_label").

.output test_label_check
