//-----------------------------------------------------------------------------
// Copyright 2021 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//-----------------------------------------------------------------------------

/*
 * This is a small low-level IR that contains particles with flattened 
 * input/output access path lists. It can be translated directly into datalog
 * relations that similarly represent particles with flattened lists of full 
 * access path names.
 *
 * There is likely a higher-level IR from which this compiles, and the higher 
 * level IR can be generated by deserializing protobufs.
 */

#ifndef LOW_GRAPH_IR_H_
#define LOW_GRAPH_IR_H_

#include <string>
#include <vector>

namespace raksha_graph_ir {

class LowGraphAccessPath {
    public:
        LowGraphAccessPath(std::string _full_path_name) : 
            full_path_name(_full_path_name) {};
        const std::string& GetName() const;
        const std::string& PrettyPrint() const;
    private:
        const std::string full_path_name;
};

class LowGraphNode {
    public:
       LowGraphNode(std::string _name,
               std::vector<LowGraphAccessPath> _inputs,
               std::vector<LowGraphAccessPath> _outputs) :
           name(_name), inputs(_inputs), outputs(_outputs) {};
       const std::string& GetName() const;
       const std::vector<LowGraphAccessPath>& GetInputs() const;
       const std::vector<LowGraphAccessPath>& GetOutputs() const;
       std::string PrettyPrint() const;
    private:
       const std::string name;
       const std::vector<LowGraphAccessPath> inputs;
       const std::vector<LowGraphAccessPath> outputs;
       static std::string PrettyPrintAPVec(
                std::vector<LowGraphAccessPath>);
};

typedef std::vector<LowGraphNode> LowGraph;

} // raksha_graph_ir

#endif // LOW_GRAPH_IR_H_

