//-----------------------------------------------------------------------------
// Copyright 2021 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//-----------------------------------------------------------------------------
.type DummyType <: symbol
.decl grounded_dummy(dummy_param: DummyType)
.decl says_canActAs(speaker: Principal, p1: Principal, p2: Principal)
.decl says_isNumber(speaker: Principal, x: number)
says_ownsTag("prin1", "particle", "foo").
says_isPrincipal("prin1", "prin1").
says_isTag("prin1", "foo").
says_isPrincipal("prin1", "particle").
grounded_dummy("dummy_var").
