#!/bin/sh
#-------------------------------------------------------------------------------
# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#-------------------------------------------------------------------------------

HOOK_NAMES=(
  applypatch-msg
  pre-applypatch
  post-applypatch
  pre-commit
  prepare-commit-msg
  commit-msg
  post-commit
  pre-rebase
  post-checkout
  post-merge
  pre-receive
  update
  post-receive
  post-update
  pre-auto-gc
)
ROOT=$(git rev-parse --show-toplevel)
HOOK_DIR="$ROOT/.git/hooks"
WRAPPER="$ROOT/scripts/hook-wrapper"

for hook in ${HOOK_NAMES[@]}; do
    # If the hook already exists, is executable, and is not a symlink
    if [ ! -h $HOOK_DIR/$hook -a -x $HOOK_DIR/$hook ]; then
        mv $HOOK_DIR/$hook $HOOK_DIR/$hook.local
    fi
    # Create the symlink, overwriting the file if it exists.
    ln -s $WRAPPER $HOOK_DIR/$hook
done
