//-----------------------------------------------------------------------------
// Copyright 2021 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//-----------------------------------------------------------------------------
// Used to ensure that a test with a duplicated test case name fails if one case fails and the
// other succeeds. This matches closely the case we want to prevent from happening in the repo, as
// if we did not take care to prevent this, one instance of the name would be added to the
// testSucceeds set, masking the other failure.
#include "src/analysis/souffle/taint.dl"
#include "src/analysis/souffle/fact_test_helper.dl"

TEST_CASE("one_equal_to_one") :- 1 = 1.
TEST_CASE("one_equal_to_one") :- 1 = 2.
