//-----------------------------------------------------------------------------
// Copyright 2021 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//-----------------------------------------------------------------------------
// Original Arcs manifest file:
// Note: Replaced the tags "trusted" and "loggable" to "userSelection" and "screenContent" to test
// how confidentiality tags would move along the dataflow graph provided by this manifest.
// TODO(Issue #50): The original test was checking that integrity tags would not propagate to
// parents; that is, just because "R.P2.foo.a" is trustworthy, that does not mean that all of
// "R.P2.foo" is. We should update this test to test this originally-intended integrity aspect once
// we have implemented it.
// #Ingress: P1
// #FAIL: hc:P2.foo is userSelection
//particle P1
//  foo: writes Foo {a: Text, b: Number}
//  claim foo.a is userSelection
//  claim foo.b is screenContent
//particle P2
//  foo: reads Foo {a: Text, b: Number}
//  check foo is userSelection
//recipe R
//  P1
//    foo: writes h
//  P2
//    foo: reads h
#include "src/analysis/souffle/taint.dl"
#include "src/analysis/souffle/fact_test_helper.dl"

says_hasTag("P1", "R.P1.foo.a", "P1", "userSelection").
says_hasTag("P1", "R.P1.foo.b", "P1", "screenContent").

edge("R.P1.foo.a", "R.h.Foo.a").
edge("R.P1.foo.b", "R.h.Foo.b").

edge("R.h.Foo.a", "R.P2.foo.a").
edge("R.h.Foo.b", "R.P2.foo.b").

CHECK_TAG_PRESENT("R.P2.foo.a", "P1", "userSelection").
CHECK_TAG_PRESENT("R.P2.foo.b", "P1", "screenContent").

CHECK_TAG_PRESENT("R.P2.foo", "P1", "userSelection").
CHECK_TAG_PRESENT("R.P2.foo", "P1", "screenContent").
