// Original Arcs manifest:
// Note: We have changed this test from the original Arcs manifest test by renaming the tags
// "trusted" and "notTrusted" to "screenContent" and "userSelection", as the tags in this test spread like
// confidentiality tags.
// Fails when different tag is claimed.
// #Ingress: P1
// #Fail: hc:P2.bar is screenContent
//particle P1
//  foo: writes Foo {}
//  claim foo is userSelection
//particle P2
//  bar: reads Foo {}
//  check bar is screenContent
//recipe R
//  P1
//    foo: writes h
//  P2
//    bar: reads h
//
// The below fact-based test is hand-derived from the above Arcs manifest test.
#include "taint.dl"
#include "fact_test_helper.dl"

claimHasTag("R.P1.foo", "userSelection").
edge("R.P1.foo", "R.h.Foo").
edge("R.h.Foo", "R.P2.bar").

CHECK_TAG_NOT_PRESENT("R.P2.bar", "screenContent").
CHECK_TAG_PRESENT("R.P2.bar", "userSelection").
