#include "src/analysis/souffle/taint.dl"
#include "src/analysis/souffle/fact_test_helper.dl"
#include "src/analysis/souffle/tests/arcs_fact_tests/integrity_tag_prop_helper.dl"

// Create a simple cycle with an additional AccessPath connected to it (call
// this an "onramp") and show that the onramp affects propagation of the
// integrity tags through the cycle.
isAccessPath("a").
isAccessPath("b").
isAccessPath("c").
isAccessPath("d").

edge("a", "b").
edge("b", "c").
edge("d", "c").
edge("c", "a").

hasAppliedIntegrityTag("a", "defaultOwner", "integ1").
hasAppliedIntegrityTag("d", "defaultOwner", "integ1").
expectHasIntegrityTag("a", "defaultOwner", "integ1").
expectHasIntegrityTag("b", "defaultOwner", "integ1").
expectHasIntegrityTag("c", "defaultOwner", "integ1").
expectHasIntegrityTag("d", "defaultOwner", "integ1").

hasAppliedIntegrityTag("a", "defaultOwner", "integ2").
expectHasIntegrityTag("a", "defaultOwner", "integ2").
expectHasIntegrityTag("b", "defaultOwner", "integ2").
