#include "taint.dl"
#include "fact_test_helper.dl"
#include "integrity_tag_prop_helper.dl"

// "d" has 3 children, "a", "b", and "c"
phi("phi_temp", "a", "b").
phi("d", "phi_temp", "c").

hasAppliedIntegrityTag("a", "defaultOwner", "integ1").
hasAppliedIntegrityTag("b", "defaultOwner", "integ1").
hasAppliedIntegrityTag("c", "defaultOwner", "integ1").

expectHasIntegrityTag("a", "defaultOwner", "integ1").
expectHasIntegrityTag("b", "defaultOwner", "integ1").
expectHasIntegrityTag("phi_temp", "defaultOwner", "integ1").
expectHasIntegrityTag("c", "defaultOwner", "integ1").
expectHasIntegrityTag("d", "defaultOwner", "integ1").

hasAppliedIntegrityTag("a", "defaultOwner", "integ2").
hasAppliedIntegrityTag("b", "defaultOwner", "integ2").
expectHasIntegrityTag("a", "defaultOwner", "integ2").
expectHasIntegrityTag("b", "defaultOwner", "integ2").
expectHasIntegrityTag("phi_temp", "defaultOwner", "integ2").

hasAppliedIntegrityTag("a", "defaultOwner", "integ3").
hasAppliedIntegrityTag("c", "defaultOwner", "integ3").
expectHasIntegrityTag("a", "defaultOwner", "integ3").
expectHasIntegrityTag("c", "defaultOwner", "integ3").

hasAppliedIntegrityTag("b", "defaultOwner", "integ4").
hasAppliedIntegrityTag("c", "defaultOwner", "integ4").
expectHasIntegrityTag("b", "defaultOwner", "integ4").
expectHasIntegrityTag("c", "defaultOwner", "integ4").

hasAppliedIntegrityTag("d", "defaultOwner", "integ5").
expectHasIntegrityTag("d", "defaultOwner", "integ5").
