//-----------------------------------------------------------------------------
// Copyright 2021 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//-----------------------------------------------------------------------------
#include "src/analysis/souffle/taint.dl"
#include "src/analysis/souffle/fact_test_helper.dl"

.decl expectHasIntegrityTag(ap: AccessPath, owner: Principal, tag: IntegrityTag)

// Ensure that the expected and actual integrity tag relations are equivalent.
.decl expectedTagNotPresent(ap: AccessPath, owner: Principal, tag: IntegrityTag)
expectedTagNotPresent(ap, owner, tag) :-
  expectHasIntegrityTag(ap, owner, tag), !mustHaveIntegrityTag(ap, owner, tag).

.decl unexpectedTagPresent(ap: AccessPath, owner: Principal, tag: IntegrityTag)
unexpectedTagPresent(ap, owner, tag) :-
  mustHaveIntegrityTag(ap, owner, tag), !expectHasIntegrityTag(ap, owner, tag).

.output expectedTagNotPresent(IO=stdout, delimiter=",")
.output unexpectedTagPresent(IO=stdout, delimiter=",")

// These help with debugging if the test fails.
.output hasAppliedIntegrityTag(IO=stdout, delimiter=",")
.output mustHaveIntegrityTag(IO=stdout, delimiter=",")

TEST_CASE("expected_tag_not_present_is_empty") :- count : { expectedTagNotPresent(_, _, _) } = 0.
TEST_CASE("unexpected_tag_present_is_empty") :- count : { unexpectedTagPresent(_, _, _) } = 0.
TEST_CASE("num_expected_matches_num_actual_and_not_zero") :-
  count_expected = count : { expectHasIntegrityTag(_, _, _) },
  count_actual = count : { mustHaveIntegrityTag(_, _, _) },
  count_expected != 0,
  count_actual != 0,
  count_expected = count_actual.
