#include "src/analysis/souffle/taint.dl"
#include "src/analysis/souffle/fact_test_helper.dl"
#include "src/analysis/souffle/tests/arcs_fact_tests/integrity_tag_prop_helper.dl"

isAccessPath("a").
isAccessPath("b").

edge("a", "b").

hasAppliedIntegrityTag("a", "defaultOwner", "integ1").
expectHasIntegrityTag("a", "defaultOwner", "integ1").
expectHasIntegrityTag("b", "defaultOwner", "integ1").

hasAppliedIntegrityTag("b", "defaultOwner", "integ2").
expectHasIntegrityTag("b", "defaultOwner", "integ2").
