//-----------------------------------------------------------------------------
// Copyright 2021 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//-----------------------------------------------------------------------------
#include "src/analysis/souffle/taint.dl"
#include "src/analysis/souffle/fact_test_helper.dl"
#include "src/analysis/souffle/tests/arcs_fact_tests/integrity_tag_prop_helper.dl"

// Create a simple cycle with an additional AccessPath connected to it (call
// this an "onramp") and show that the onramp affects propagation of the
// integrity tags through the cycle.
isAccessPath("a").
isAccessPath("b").
isAccessPath("c").
isAccessPath("d").

edge("a", "b").
edge("b", "c").
edge("d", "c").
edge("c", "a").

hasAppliedIntegrityTag("a", "defaultOwner", ["integ1", nil]).
hasAppliedIntegrityTag("d", "defaultOwner", ["integ1", nil]).
expectHasIntegrityTag("a", "defaultOwner", ["integ1", nil]).
expectHasIntegrityTag("b", "defaultOwner", ["integ1", nil]).
expectHasIntegrityTag("c", "defaultOwner", ["integ1", nil]).
expectHasIntegrityTag("d", "defaultOwner", ["integ1", nil]).

hasAppliedIntegrityTag("a", "defaultOwner", ["integ2", nil]).
expectHasIntegrityTag("a", "defaultOwner", ["integ2", nil]).
expectHasIntegrityTag("b", "defaultOwner", ["integ2", nil]).
