#include "src/analysis/souffle/taint.dl"
#include "src/analysis/souffle/fact_test_helper.dl"
#include "src/analysis/souffle/tests/arcs_fact_tests/integrity_tag_prop_helper.dl"

// Create two simple cycles and watch integrity tags flow along them.
isAccessPath("a").
isAccessPath("b").
isAccessPath("c").
isAccessPath("d").
isAccessPath("e").

edge("a", "b").
edge("b", "c").
edge("c", "a").
edge("c", "d").
edge("d", "e").
edge("e", "c").

hasAppliedIntegrityTag("a", "defaultOwner", "integ1").
hasAppliedIntegrityTag("d", "defaultOwner", "integ1").
expectHasIntegrityTag("a", "defaultOwner", "integ1").
expectHasIntegrityTag("b", "defaultOwner", "integ1").
expectHasIntegrityTag("c", "defaultOwner", "integ1").
expectHasIntegrityTag("d", "defaultOwner", "integ1").
expectHasIntegrityTag("e", "defaultOwner", "integ1").

hasAppliedIntegrityTag("c", "defaultOwner", "integ2").
expectHasIntegrityTag("a", "defaultOwner", "integ2").
expectHasIntegrityTag("b", "defaultOwner", "integ2").
expectHasIntegrityTag("c", "defaultOwner", "integ2").
expectHasIntegrityTag("d", "defaultOwner", "integ2").
expectHasIntegrityTag("e", "defaultOwner", "integ2").

hasAppliedIntegrityTag("a", "defaultOwner", "integ3").
expectHasIntegrityTag("a", "defaultOwner", "integ3").
expectHasIntegrityTag("b", "defaultOwner", "integ3").

hasAppliedIntegrityTag("d", "defaultOwner", "integ4").
expectHasIntegrityTag("d", "defaultOwner", "integ4").
expectHasIntegrityTag("e", "defaultOwner", "integ4").
