//-----------------------------------------------------------------------------
// Copyright 2021 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//-----------------------------------------------------------------------------
#include "src/analysis/souffle/taint.dl"
#include "src/analysis/souffle/fact_test_helper.dl"
#include "src/analysis/souffle/tests/arcs_fact_tests/integrity_tag_prop_helper.dl"

isAccessPath("a").
isAccessPath("b").

edge("a", "b").

hasAppliedIntegrityTag("a", "defaultOwner", ["integ1", nil]).
expectHasIntegrityTag("a", "defaultOwner", ["integ1", nil]).
expectHasIntegrityTag("b", "defaultOwner", ["integ1", nil]).

hasAppliedIntegrityTag("b", "defaultOwner", ["integ2", nil]).
expectHasIntegrityTag("b", "defaultOwner", ["integ2", nil]).
