#include "taint.dl"
#include "fact_test_helper.dl"
#include "integrity_tag_prop_helper.dl"

isAccessPath("a").
isAccessPath("b").

edge("a", "b").

directHasIntegrityTag("a", "defaultOwner", "integ1").
expectHasIntegrityTag("a", "defaultOwner", "integ1").
expectHasIntegrityTag("b", "defaultOwner", "integ1").

directHasIntegrityTag("b", "defaultOwner", "integ2").
expectHasIntegrityTag("b", "defaultOwner", "integ2").
