//-----------------------------------------------------------------------------
// Copyright 2021 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//-----------------------------------------------------------------------------
#include "src/analysis/souffle/taint.dl"
#include "src/analysis/souffle/fact_test_helper.dl"
#include "src/analysis/souffle/tests/arcs_fact_tests/integrity_tag_prop_helper.dl"

// Show that integrity tags with different owners are treated as two different
// integrity tags.
edge("a", "r").
edge("b", "r").

hasAppliedIntegrityTag("a", "owner1", ["integ1", nil]).
hasAppliedIntegrityTag("b", "owner2", ["integ1", nil]).

expectHasIntegrityTag("a", "owner1", ["integ1", nil]).
expectHasIntegrityTag("b", "owner2", ["integ1", nil]).

// Show that removing an integrity tag with a different owner does not block
// its propagation.
edge("c", "d").
edge("d", "e").

hasAppliedIntegrityTag("c", "owner1", ["integ2", nil]).
removeIntegrityTag("d", "owner2", ["integ2", nil]).

expectHasIntegrityTag("c", "owner1", ["integ2", nil]).
expectHasIntegrityTag("d", "owner1", ["integ2", nil]).
expectHasIntegrityTag("e", "owner1", ["integ2", nil]).
