#include "src/analysis/souffle/taint.dl"
#include "src/analysis/souffle/fact_test_helper.dl"
#include "src/analysis/souffle/tests/arcs_fact_tests/integrity_tag_prop_helper.dl"

// Show that integrity tags with different owners are treated as two different
// integrity tags.
edge("a", "r").
edge("b", "r").

hasAppliedIntegrityTag("a", "owner1", "integ1").
hasAppliedIntegrityTag("b", "owner2", "integ1").

expectHasIntegrityTag("a", "owner1", "integ1").
expectHasIntegrityTag("b", "owner2", "integ1").

// Show that removing an integrity tag with a different owner does not block
// its propagation.
edge("c", "d").
edge("d", "e").

hasAppliedIntegrityTag("c", "owner1", "integ2").
removeIntegrityTag("d", "owner2", "integ2").

expectHasIntegrityTag("c", "owner1", "integ2").
expectHasIntegrityTag("d", "owner1", "integ2").
expectHasIntegrityTag("e", "owner1", "integ2").
