// claim propagates through a chain of particles
// Note: we have changed this test from the original Arcs manifest test by renaming the tag
// "trusted" to "userSelection", as the tag in this test spreads like a confidentiality-aspect tag.
// #Ingress: P1
// #OK
//particle P1
//  foo: writes Foo {}
//  claim foo is userSelection
//particle P2
//  bar: reads Foo {}
//  foo: writes Foo {}
//particle P3
//  bar: reads Foo {}
//  check bar is userSelection
//recipe R
//  P1
//    foo: writes h1
//  P2
//    bar: reads h1
//    foo: writes h2
//  P3
//    bar: reads h2
//
// The below fact-based test is hand-derived from the above Arcs manifest test.
#include "src/analysis/souffle/taint.dl"
#include "src/analysis/souffle/fact_test_helper.dl"

says_hasTag("P1", "R.P1.foo", "P1", "userSelection").
edge("R.P1.foo", "R.h1.Foo").
edge("R.h1.Foo", "R.P2.bar").
edge("R.P2.bar", "R.P2.foo").
edge("R.P2.foo", "R.h2.Foo").
edge("R.h2.Foo", "R.P3.bar").

// This test passes if R.P3.bar has the trusted tag.
CHECK_TAG_PRESENT("R.P3.bar", "P1", "userSelection").
