//-----------------------------------------------------------------------------
// Copyright 2022 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//-----------------------------------------------------------------------------

#include "src/analysis/souffle/taint.dl"
#include "src/analysis/souffle/fact_test_helper.dl"

#define TEST_SINGLE_RESULT_FOR_OPERATION(test_name, operation, relation, expected) \
  TEST_CASE(cat(test_name, cat("_", #relation))) :- \
    count : { relation(operation, _) } = 1, relation(operation, expected)

#define CREATE_AND_TEST_OPERATOR_INNER(test_name, operation, actor, operator, result, operandList, attrList) \
  isOperation(operation). \
  TEST_SINGLE_RESULT_FOR_OPERATION(test_name, (operation), operationHasActor, actor). \
  TEST_SINGLE_RESULT_FOR_OPERATION(test_name, (operation), operationHasOperator, operator). \
  TEST_SINGLE_RESULT_FOR_OPERATION(test_name, (operation), operationHasResult, result). \
  TEST_SINGLE_RESULT_FOR_OPERATION(test_name, (operation), operationHasOperandList, (operandList)). \
  TEST_SINGLE_RESULT_FOR_OPERATION(test_name, (operation), operationHasAttributeList, (attrList))

#define CREATE_AND_TEST_OPERATION(test_name, actor, operator, resultList, operandList, attrList) \
  CREATE_AND_TEST_OPERATOR_INNER(test_name, ([actor, operator, (resultList), (operandList), (attrList)]), actor, operator, result, (operandList), (attrList))

#define OPERAND_LIST1 ["operand1", nil]
#define ATTR_LIST1 [["attr1", $NumberAttributePayload(1)], nil]

CREATE_AND_TEST_OPERATION("test1", "somePrincipal", "someOperator", (["ap1", nil]), (OPERAND_LIST1), (ATTR_LIST1)).

#define ATTR_LIST2 [["someAttr", $StringAttributePayload("hello")], [["anotherAttr", $NumberAttributePayload(2)], nil]]

CREATE_AND_TEST_OPERATION("test2", "prin", "op", (["ap2", nil]), nil, (ATTR_LIST2)).

#define OPERAND_LIST2 ["input1", ["input2", nil]]
CREATE_AND_TEST_OPERATION("test3", "actor", "op2", (["ap3", nil]), (OPERAND_LIST2), nil).
