#include "src/analysis/souffle/taint.dl"
#include "src/analysis/souffle/fact_test_helper.dl"
#include "src/analysis/souffle/tests/arcs_fact_tests/integrity_tag_prop_helper.dl"

// Show that clearing an integrity tag on "b" causes it to not propagate to "c".
edge("a", "b").
edge("b", "c").

hasAppliedIntegrityTag("a", "defaultOwner", "integ").
removeIntegrityTag("b", "defaultOwner", "integ").

expectHasIntegrityTag("a", "defaultOwner", "integ").
