licenses(["notice"])

package(default_visibility = ["//src:__subpackages__"])

cc_library(
    name = "gtest",
    testonly = True,
    hdrs = [
        "gtest.h",
    ],
    deps = [
        "@com_google_googletest//:gtest_main",
    ],
)
